# Generated by Django 3.1.4 on 2020-12-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_remote_job', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('job_desc', models.TextField(blank=True, null=True)),
                ('apply_job_link', models.TextField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_website', models.CharField(blank=True, max_length=50, null=True)),
                ('company_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_scraped_data', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobcategory')),
            ],
        ),
    ]
