# Generated by Django 3.1.4 on 2020-12-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetails',
            name='apply_job_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
