# Generated by Django 3.1.4 on 2020-12-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201221_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='workdetails',
            name='job_keys',
            field=models.ManyToManyField(to='core.Job_keys'),
        ),
    ]
