# Generated by Django 3.1.4 on 2020-12-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201221_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetails',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
