# Generated by Django 3.1.4 on 2020-12-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workdetails_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetails',
            name='company_img_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
