# Generated by Django 3.1.4 on 2020-12-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_workdetails_company_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetails',
            name='is_remote_job',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
